# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

2.4.4
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/bb/km69qtt53nlbxc29ljr4c9d00000gn/T/build-env

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print(arr.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
arr=arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
arr=np.array([1,2,0,0,4,0])
indices=np.where(arr==0)
print(indices)

(array([2, 3, 5]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
Z = np.random.random((3, 3, 3))
print(Z)
print(matrix)

[[[0.26142824 0.42995593 0.45789411]
  [0.6872703  0.56697875 0.18640977]
  [0.93160766 0.47039175 0.10124141]]

 [[0.41251486 0.4728269  0.41358098]
  [0.73867044 0.4188976  0.75994381]
  [0.74305022 0.4860572  0.38880292]]

 [[0.62137604 0.95880223 0.45750494]
  [0.34342001 0.98594774 0.31107383]
  [0.01691593 0.75690148 0.42414246]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
Z=np.random.random((10, 10))
print(np.min(Z))
print(np.max(Z))

0.024472394476173887
0.9766762368711095


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
Z=np.random.random((30))
ans=np.mean(Z)
print(ans)

0.5448598530428416


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
Z=np.ones((5, 5))
Z[1:-1, 1:-1] = 0   
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode="constant", constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
Z = np.diag([1, 2, 3, 4], k=-1)

print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
Z=np.zeros((8,8))
Z[1::2, ::2]=1
print(Z)
Z[::2, 1::2]=1
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
Z=np.array((6,7,8))
index=np.unravel_index(99,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
base_stamp = np.array([[0, 1], [1, 0]])
result = np.tile(base_stamp, (4, 4))
print(result)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
Z=np.random.random((5,5))
Z_mean,Z_std=Z.mean(),Z.std()
Z=(Z-Z_mean)/Z_std
print(Z)

[[ 1.46074186 -1.59061885 -0.38032294  1.4614698  -0.46222155]
 [-0.16168966  0.92531491  0.65227715  1.60092143 -0.6592146 ]
 [-0.2059617  -0.59900629  0.50573943 -1.27979902 -1.39117   ]
 [ 0.90115027 -1.05518603  1.49290412  1.10333454 -0.97931557]
 [-0.50498292  0.52618781  0.08541577 -1.55699804  0.11103007]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

Image = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color)
print(Image["r"])
print(Image["g"])
print(Image["b"])
print(Image["a"])
print(Image)

[255   0   0]
[  0 255   0]
[  0   0 255]
[255 255 255]
[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
matrix1 = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [1, 2, 3],])

matrix2 = np.array([
        [1, 2],
        [4, 5],
        [7, 8],
])

product = np.dot(matrix1, matrix2)
print(product)

[[ 30  36]
 [ 66  81]
 [102 126]
 [ 30  36]
 [ 30  36]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
Z=np.array([1,2,3,4,5,6,7,8,9])
Z=Z[(3<=Z) & (Z<=8)]
print(Z)

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[3 4 5 6 7 8]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [32]:
#print(sum(range(5), -1))
#from numpy import *
#print(sum(range(5), -1))

print(sum(range(5), -1))  # 明确知道是原生 sum，输出 9
print(np.sum(range(5), -1))  # 明确知道是 NumPy 矩阵求和，输出 10


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
Z=np.array([1,2,3,4,5,6,7,8,9])
print(
    Z**Z,
    2 << Z >> 2,
    Z <- Z,
    1j*Z,
    Z/1/1,
)

[        1         4        27       256      3125     46656    823543
  16777216 387420489] [  1   2   4   8  16  32  64 128 256] [False False False False False False False False False] [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j] [1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[0.]


/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_6638/1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_6638/1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_6638/1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
Z = np.array([-1.2, -1.8, 1.2, 1.8, 0.0])
result2 = np.copysign(np.ceil(np.abs(Z)), Z)

print(result2)

[-2. -2.  2.  2.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [42]:
X=np.arange(0,10)
Y=np.arange(0,11,2)
print(X)
print(Y)
result = np.intersect1d(X, Y)
print(result)
result = np.intersect1d(X, Y,return_indices=True)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
[0 2 4 6 8]
(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]), array([0, 1, 2, 3, 4]))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_6638/1251884223.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_6638/1251884223.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [48]:
# 1. 获取今天 (注意：'today' 会根据当前系统时间生成日期)
today = np.datetime64("today", "D")

# 2. 计算昨天 (今天减去 1 天)
yesterday = today - np.timedelta64(1, "D")

# 3. 计算明天 (今天加上 1 天)
tomorrow = today + np.timedelta64(1, "D")

print("昨天: ", yesterday)
print("今天: ", today)
print("明天: ", tomorrow)


昨天:  2026-04-23
今天:  2026-04-24
明天:  2026-04-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [49]:
dates=np.arange('2016-07-01','2016-08-01',dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [51]:
A = np.ones(3) * 10  
B = np.ones(3) * 2 
np.add(A, B, out=B) 
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[-120. -120. -120.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [58]:
Z=np.random.uniform(0,10,10)
print(Z)
X1=np.floor(Z)
print(X1)
X2=np.trunc(Z)
print(X2)
X3=Z.astype(int)
print(X3)

[6.64566804 3.31314979 4.82018812 7.16084267 2.18734504 8.69804309
 6.01515911 3.88807153 5.40204013 0.03378585]
[6. 3. 4. 7. 2. 8. 6. 3. 5. 0.]
[6. 3. 4. 7. 2. 8. 6. 3. 5. 0.]
[6 3 4 7 2 8 6 3 5 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [63]:
matrix = np.zeros((5, 5)) + np.arange(5)
print(matrix)
base_stamp=np.array([0,1,2,3,4])
Z=np.tile(base_stamp,(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [67]:
def generate_integers():
    for i in range(10):
        yield i  # 每次只“吐”出一个数字，而不是一次性生成一个大列表


# 第二步：使用 np.fromiter 将生成器转化为 NumPy 数组
# 必须指定 dtype，这是为了让 NumPy 在底层直接分配连续的内存
Z = np.fromiter(generate_integers(), dtype=float, count=-1)

print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [74]:
Z=np.random.random(10)
print(Z)
Z = np.linspace(0, 1, 11, endpoint=False)[1:] # linspace 生成一个等差数列，参数解释如下：
# 0: 起始值
# 1: 终止值（不包含）
# 11: 生成的元素数量
# endpoint=False: 是否包含终止值（默认是 True，表示包含）
print(Z)

[0.90669284 0.84156698 0.5831503  0.78806003 0.90624557 0.88980421
 0.89043064 0.21558126 0.36683609 0.34323213]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [75]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.13772694 0.17164277 0.24835725 0.32119082 0.56631474 0.61703517
 0.68293641 0.79083159 0.85019212 0.96894738]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [77]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.add.reduce(mat, axis=0))
print(np.add.reduce(mat, axis=1))

[12 15 18]
[ 6 15 24]


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
A = np.array([0.1+0.2])
B = np.array([0.3])
print(np.array_equal(A, B)) #严格相等
print(np.allclose(A, B)) # 接近即可

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
X_immutable = np.array([1, 2, 3])
Z.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [86]:
matrix=np.random.random((10,2))
X, Y = matrix[:, 0], matrix[:, 1]
r=np.sqrt(X**2 + Y**2)
t=np.arctan2(Y, X)
ans=np.c_[r, t]
print(ans)


[[0.89643495 0.30470836]
 [1.02445292 1.0247086 ]
 [0.95751941 0.71690421]
 [1.12349262 0.62967112]
 [0.40895495 1.2326248 ]
 [0.1393883  0.6192472 ]
 [1.10239251 0.46010926]
 [1.14806347 0.89614388]
 [0.83987305 0.15535267]
 [0.82571373 0.23539823]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [87]:
Z=np.random.random(10)
indices=np.argmax(Z)
Z[indices]=0
print(Z)

[0.25557067 0.05386981 0.42783288 0.21480958 0.         0.26454851
 0.56058607 0.60091871 0.35049709 0.66450871]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [94]:
n = 5
x = np.linspace(0, 1, n)
y = np.array([1, 2, 3, 4, 5])
X, Y = np.meshgrid(x, y)
print(x)
print(y)
print(X)
print(Y)

[0.   0.25 0.5  0.75 1.  ]
[1 2 3 4 5]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [97]:
A = np.array([1, 2, 3])
B = np.array([10, 20])
C = 1.0 / np.subtract.outer(A, B)
print("柯西矩阵的形状:", C.shape)
print(C)  # 打印左上角 3x3 看看

柯西矩阵的形状: (3, 2)
[[-0.11111111 -0.05263158]
 [-0.125      -0.05555556]
 [-0.14285714 -0.05882353]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [101]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import sys

Z = np.zeros((40, 40))

# 官方标准动作：将打印阈值设置为系统的最大尺寸
np.set_printoptions(threshold=sys.maxsize)

# 现在打印 Z，绝对不会出现省略号了！
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [106]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
print(Z)
print(v)
index = (np.abs(Z - v)).argmin()
print(Z[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
38.93804563154413
39


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)