# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

2.4.4
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/bb/km69qtt53nlbxc29ljr4c9d00000gn/T/build-env

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(arr.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr=arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr=np.array([1,2,0,0,4,0])
indices=np.where(arr==0)
print(indices)

(array([2, 3, 5]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
Z = np.random.random((3, 3, 3))
print(Z)
print(matrix)

[[[0.60510394 0.08860873 0.02398076]
  [0.13437677 0.23361522 0.23131032]
  [0.3635603  0.64063422 0.99759152]]

 [[0.77409788 0.76110301 0.83955105]
  [0.36282688 0.88644693 0.31280051]
  [0.89465214 0.90983647 0.7762431 ]]

 [[0.10881031 0.81659213 0.89445011]
  [0.92560575 0.35793832 0.76243487]
  [0.73063956 0.60845915 0.37199112]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
Z=np.random.random((10, 10))
print(np.min(Z))
print(np.max(Z))

0.016752060137113056
0.998142655087331


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
Z=np.random.random((30))
ans=np.mean(Z)
print(ans)

0.46350592550725034


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
Z=np.ones((5, 5))
Z[1:-1, 1:-1] = 0   
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode="constant", constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
Z = np.diag([1, 2, 3, 4], k=-1)

print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
Z=np.zeros((8,8))
Z[1::2, ::2]=1
print(Z)
Z[::2, 1::2]=1
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
Z=np.array((6,7,8))
index=np.unravel_index(99,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
base_stamp = np.array([[0, 1], [1, 0]])
result = np.tile(base_stamp, (4, 4))
print(result)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
Z=np.random.random((5,5))
Z_mean,Z_std=Z.mean(),Z.std()
Z=(Z-Z_mean)/Z_std
print(Z)

[[-1.17252772 -0.14875373  2.48695513  1.50544172  1.44217781]
 [ 0.91692059  1.07601412 -0.90753713  0.0884108   0.36393626]
 [-1.04234749  0.14829305 -0.95357187 -0.48893445 -0.66051406]
 [-0.48211708  1.35259379 -1.09209181 -0.89881722 -0.35598246]
 [ 1.19582946 -0.50193585 -0.94138529 -0.80152207 -0.1285345 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

Image = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color)
print(Image["r"])
print(Image["g"])
print(Image["b"])
print(Image["a"])
print(Image)

[255   0   0]
[  0 255   0]
[  0   0 255]
[255 255 255]
[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
matrix1 = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [1, 2, 3],])

matrix2 = np.array([
        [1, 2],
        [4, 5],
        [7, 8],
])

product = np.dot(matrix1, matrix2)
print(product)

[[ 30  36]
 [ 66  81]
 [102 126]
 [ 30  36]
 [ 30  36]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z=np.array([1,2,3,4,5,6,7,8,9])
Z=Z[(3<=Z) & (Z<=8)]
print(Z)

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[3 4 5 6 7 8]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
#print(sum(range(5), -1))
#from numpy import *
#print(sum(range(5), -1))

print(sum(range(5), -1))  # 明确知道是原生 sum，输出 9
print(np.sum(range(5), -1))  # 明确知道是 NumPy 矩阵求和，输出 10


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z=np.array([1,2,3,4,5,6,7,8,9])
print(
    Z**Z,
    2 << Z >> 2,
    Z <- Z,
    1j*Z,
    Z/1/1,
)

[        1         4        27       256      3125     46656    823543
  16777216 387420489] [  1   2   4   8  16  32  64 128 256] [False False False False False False False False False] [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j] [1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[0.]


/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_99726/1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_99726/1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_99726/1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
Z = np.array([-1.2, -1.8, 1.2, 1.8, 0.0])
result2 = np.copysign(np.ceil(np.abs(Z)), Z)

print(result2)

[-2. -2.  2.  2.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
X=np.arange(0,10)
Y=np.arange(0,11,2)
print(X)
print(Y)
result = np.intersect1d(X, Y)
print(result)
result = np.intersect1d(X, Y,return_indices=True)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
[0 2 4 6 8]
(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]), array([0, 1, 2, 3, 4]))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_99726/1251884223.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_99726/1251884223.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
# 1. 获取今天 (注意：'today' 会根据当前系统时间生成日期)
today = np.datetime64("today", "D")

# 2. 计算昨天 (今天减去 1 天)
yesterday = today - np.timedelta64(1, "D")

# 3. 计算明天 (今天加上 1 天)
tomorrow = today + np.timedelta64(1, "D")

print("昨天: ", yesterday)
print("今天: ", today)
print("明天: ", tomorrow)


昨天:  2026-05-10
今天:  2026-05-11
明天:  2026-05-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
dates=np.arange('2016-07-01','2016-08-01',dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3) * 10  
B = np.ones(3) * 2 
np.add(A, B, out=B) 
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[-120. -120. -120.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
Z=np.random.uniform(0,10,10)
print(Z)
X1=np.floor(Z)
print(X1)
X2=np.trunc(Z)
print(X2)
X3=Z.astype(int)
print(X3)

[6.35847932 0.84646156 6.99724249 0.58230778 3.13890286 3.98996271
 3.51821884 7.62649221 9.4814848  6.3937628 ]
[6. 0. 6. 0. 3. 3. 3. 7. 9. 6.]
[6. 0. 6. 0. 3. 3. 3. 7. 9. 6.]
[6 0 6 0 3 3 3 7 9 6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
matrix = np.zeros((5, 5)) + np.arange(5)
print(matrix)
base_stamp=np.array([0,1,2,3,4])
Z=np.tile(base_stamp,(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate_integers():
    for i in range(10):
        yield i  # 每次只“吐”出一个数字，而不是一次性生成一个大列表


# 第二步：使用 np.fromiter 将生成器转化为 NumPy 数组
# 必须指定 dtype，这是为了让 NumPy 在底层直接分配连续的内存
Z = np.fromiter(generate_integers(), dtype=float, count=-1)

print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
Z=np.random.random(10)
print(Z)
Z = np.linspace(0, 1, 11, endpoint=False)[1:] # linspace 生成一个等差数列，参数解释如下：
# 0: 起始值
# 1: 终止值（不包含）
# 11: 生成的元素数量
# endpoint=False: 是否包含终止值（默认是 True，表示包含）
print(Z)

[0.9215846  0.14973821 0.80355383 0.08703916 0.64987769 0.3221391
 0.88604657 0.22567696 0.62784555 0.21594324]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.00767379 0.14772014 0.14851335 0.15391421 0.31207128 0.66231531
 0.67122965 0.69495189 0.96592578 0.97536567]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.add.reduce(mat, axis=0))
print(np.add.reduce(mat, axis=1))

[12 15 18]
[ 6 15 24]


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [42]:
A = np.array([0.1+0.2])
B = np.array([0.3])
print(np.array_equal(A, B)) #严格相等
print(np.allclose(A, B)) # 接近即可

False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
X_immutable = np.array([1, 2, 3])
Z.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
matrix=np.random.random((10,2))
X, Y = matrix[:, 0], matrix[:, 1]
r=np.sqrt(X**2 + Y**2)
t=np.arctan2(Y, X)
ans=np.c_[r, t]
print(ans)


[[0.61531038 1.50511968]
 [1.09409229 0.73088689]
 [0.52656964 0.3022629 ]
 [0.74278351 0.64039945]
 [1.15265041 0.97986414]
 [0.66207392 0.08634129]
 [0.85298611 1.01395124]
 [0.83676911 1.53434324]
 [0.60507234 0.83460128]
 [0.30844272 1.13360175]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
Z=np.random.random(10)
indices=np.argmax(Z)
Z[indices]=0
print(Z)

[0.40755273 0.50273292 0.11610956 0.01970304 0.46314527 0.22590989
 0.         0.55526601 0.01375708 0.03945444]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
n = 5
x = np.linspace(0, 1, n)
y = np.array([1, 2, 3, 4, 5])
X, Y = np.meshgrid(x, y)
print(x)
print(y)
print(X)
print(Y)

[0.   0.25 0.5  0.75 1.  ]
[1 2 3 4 5]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
A = np.array([1, 2, 3])
B = np.array([10, 20])
C = 1.0 / np.subtract.outer(A, B)
print("柯西矩阵的形状:", C.shape)
print(C)  # 打印左上角 3x3 看看

柯西矩阵的形状: (3, 2)
[[-0.11111111 -0.05263158]
 [-0.125      -0.05555556]
 [-0.14285714 -0.05882353]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
import sys

Z = np.zeros((40, 40))

# 官方标准动作：将打印阈值设置为系统的最大尺寸
np.set_printoptions(threshold=sys.maxsize)

# 现在打印 Z，绝对不会出现省略号了！
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
print(Z)
print(v)
index = (np.abs(Z - v)).argmin()
print(Z[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
56.30370031421547
56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
custom_dtype = np.dtype(
    [
        ("position", [("x", np.float64), ("y", np.float64)]),
        ("color",[("r", np.uint8),("g", np.uint8),("b", np.uint8),],),
    ]
)
Z = np.zeros(
    10,
    custom_dtype
)
print(Z)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
# Much faster with scipy
import scipy

# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial


Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X - X.T) ** 2 + (Y - Y.T) ** 2)
print(D)



Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z, Z)
print(D)


[[0.         0.28081549 0.70648154 0.26574351 0.66239723 0.68396798
  0.7020722  0.5709216  0.72226563 0.76917233]
 [0.28081549 0.         0.63678938 0.45672616 0.38899009 0.42809239
  0.44154275 0.3455301  0.78097708 0.6267025 ]
 [0.70648154 0.63678938 0.         0.56911822 0.62465909 0.92280657
  0.56279787 0.91870028 0.33501015 0.19323684]
 [0.26574351 0.45672616 0.56911822 0.         0.76830746 0.8847771
  0.77706477 0.79405988 0.48619526 0.69198772]
 [0.66239723 0.38899009 0.62465909 0.76830746 0.         0.33729171
  0.09314736 0.40242922 0.90295828 0.49912887]
 [0.68396798 0.42809239 0.92280657 0.8847771  0.33729171 0.
  0.42917137 0.14410396 1.15379489 0.82502974]
 [0.7020722  0.44154275 0.56279787 0.77706477 0.09314736 0.42917137
  0.         0.49455836 0.85924808 0.42103278]
 [0.5709216  0.3455301  0.91870028 0.79405988 0.40242922 0.14410396
  0.49455836 0.         1.11371338 0.84943017]
 [0.72226563 0.78097708 0.33501015 0.48619526 0.90295828 1.15379489
  0.85924808 1.113713

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [53]:
Z = (np.random.rand(10) * 100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


[38  7 82 60 96 53 96 31 43 40]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
""")
Z = np.genfromtxt(s, delimiter=",", dtype=int, filling_values=0)
print(Z)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
Z = np.arange(9).reshape(3, 3)

# 使用 np.ndenumerate 模拟 enumerate
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:

x, y = np.meshgrid(np.linspace(-1, 1, 100), np.linspace(-1, 1, 100))
Z = np.sqrt(x**2 + y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-((Z - mu) ** 2 / (2.0 * sigma**2)))

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
Z=np.arange(9).reshape(3, 3)
p=5
rolls =np.random.choice(Z.size, size=p,replace=False) 
print(rolls)
np.put(Z, rolls, -1) # np.put 目标数组 目标索引列表 替换值列表
print(Z)

[8 2 1 5 6]
[[ 0 -1 -1]
 [ 3  4 -1]
 [-1  7 -1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
n=5
matrix=np.arange(n*n).reshape(n,n)
row_mean=matrix.mean(axis=1, keepdims=True)
print(row_mean)
matrix=matrix-row_mean
print(matrix)

[[ 2.]
 [ 7.]
 [12.]
 [17.]
 [22.]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
n=1
Z=np.random.random((3,3))
print(Z)
indices=np.argsort(Z[:,n])
Z=Z[indices]
print(Z)

[[0.86535503 0.98037387 0.14091936]
 [0.78026864 0.45442682 0.99922611]
 [0.1889011  0.49034908 0.31347776]]
[[0.78026864 0.45442682 0.99922611]
 [0.1889011  0.49034908 0.31347776]
 [0.86535503 0.98037387 0.14091936]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
Z = np.array([[1, 0, 3, 4], [5, 0, 0, 8], [9, 0, 1, 2]])
has_null_column = (~Z.any(axis=0)).any()
print(has_null_column)

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


0.5141923381231719


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y

result = it.operands[2]

print("--- A ---")
print(A)
print("--- B ---")
print(B)
print("--- 迭代器计算出的结果 ---")
print(result)

--- A ---
[[0]
 [1]
 [2]]
--- B ---
[[0 1 2]]
--- 迭代器计算出的结果 ---
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, "name", "no name")


Z = NamedArray(np.arange(10), "range_10")
print(Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
Z = np.ones(10)
Y = np.random.randint(0, len(Z), 20)
Z += np.bincount(Y, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, Y, 1)
print(Z)


[4. 4. 3. 2. 2. 3. 3. 4. 4. 1.]
[7. 7. 5. 3. 3. 5. 5. 7. 7. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X) # 第一个参数索引列表，第二个参数是对应索引的值列表
print(F)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [66]:
w=3
h=3
Z=np.random.randint(0,256,(w, h,3)).astype(np.ubyte)
pixels = Z.reshape(-1, 3)
unique_colors = np.unique(pixels, axis=0)
print(len(unique_colors))

9


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [67]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
print(A)
sum = A.sum(axis=(-2, -1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


[[[[5 1 6 7]
   [6 4 8 4]
   [9 7 0 1]]

  [[1 2 5 9]
   [7 2 4 6]
   [1 7 3 7]]

  [[5 8 1 6]
   [6 8 1 4]
   [7 3 7 2]]

  [[7 1 2 6]
   [1 4 5 6]
   [0 7 1 5]]]


 [[[1 5 2 1]
   [2 9 0 6]
   [8 8 1 3]]

  [[9 3 0 5]
   [0 3 4 7]
   [9 5 8 3]]

  [[5 3 5 7]
   [6 0 9 8]
   [1 8 7 5]]

  [[5 2 7 3]
   [6 8 8 2]
   [1 5 4 3]]]


 [[[3 2 8 4]
   [6 4 5 8]
   [9 9 0 6]]

  [[4 2 4 4]
   [7 5 1 1]
   [4 8 2 1]]

  [[4 4 4 2]
   [7 3 6 5]
   [0 9 5 0]]

  [[8 1 9 2]
   [7 4 4 6]
   [5 2 9 7]]]]
[[58 54 58 45]
 [46 56 64 54]
 [64 43 49 64]]
[[58 54 58 45]
 [46 56 64 54]
 [64 43 49 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [68]:
D = np.random.uniform(0, 1, 10)
S = np.random.randint(0, 10, 10)
sums = np.bincount(S, weights=D)
counts = np.bincount(S)
means = sums / counts
print(means)

[       nan 0.38791647        nan 0.38902466 0.7920509  0.1848358
 0.9655295  0.35605227 0.27321979 0.99071129]


/var/folders/f9/hjj_p7wd08j33xxd_7r579s40000gn/T/ipykernel_99726/1874233611.py:5: RuntimeWarning: invalid value encountered in divide
  means = sums / counts


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([1.32170946, 1.38951215, 1.0729628 , 1.10801687, 1.41651096])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [70]:
Z=np.array([1,2,3,4,5])
nz=3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))
Z0[:: nz + 1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [71]:
X=np.random.randint(0,10,(5,5,3))
Y=np.random.randint(0,10,(5,5))
print(X*Y[:,:,None]) #扩展维度

[[[ 0  0  0]
  [42  0 36]
  [54 45  9]
  [ 2  0  4]
  [48 56 32]]

 [[ 0 54 24]
  [12 18  9]
  [42 21 63]
  [25 10 45]
  [30 45 40]]

 [[45 36 45]
  [ 4 10  4]
  [14 56 42]
  [48 72  8]
  [63  7 14]]

 [[ 0 14 42]
  [ 4  6 16]
  [64 40  8]
  [ 0 48 12]
  [ 5  7  2]]

 [[35 56 49]
  [16 16 16]
  [ 7  0  6]
  [10 16 10]
  [ 0 27 24]]]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
A = np.arange(25).reshape(5, 5)
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)
      

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
faces = np.random.randint(0, 100, (10, 3))
edges = np.vstack(
    [
        faces[:, [0, 1]],  # 所有三角形的第一条边
        faces[:, [1, 2]],  # 所有三角形的第二条边
        faces[:, [2, 0]],  # 所有三角形的第三条边
    ]
)
edges.sort(axis=1)
unique_edges = np.unique(edges, axis=0)
print(unique_edges)

[[ 6 52]
 [ 6 54]
 [ 8 58]
 [ 8 83]
 [ 9  9]
 [ 9 34]
 [13 48]
 [13 80]
 [22 91]
 [22 98]
 [30 65]
 [30 73]
 [39 48]
 [39 72]
 [48 72]
 [48 80]
 [50 54]
 [50 81]
 [52 54]
 [54 81]
 [58 83]
 [59 76]
 [59 80]
 [60 62]
 [60 63]
 [62 63]
 [65 73]
 [76 80]
 [91 98]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [74]:

C = np.array([1, 2, 0, 3])
A = np.repeat(np.arange(len(C)), C)

print("还原出的原始数组 A:", A)


print("验证 bincount(A) == C:", np.array_equal(np.bincount(A), C))


还原出的原始数组 A: [0 1 1 3 3 3]
验证 bincount(A) == C: True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [75]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1 :] / n


Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [76]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(1, 7)
windowed = sliding_window_view(Z, window_shape=3)
print(windowed)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [77]:
Z = np.random.randint(0, 2, 100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out=Z)


array([-0.97143711,  0.47174704, -0.85150154, -0.78097329, -0.5255653 ,
        0.2103885 ,  0.06757207, -0.79646412,  0.50124389,  0.35313086,
       -0.22976947, -0.53391145, -0.72151348, -0.05435134, -0.86298543,
        0.3240632 , -0.90168892,  0.45830374, -0.35291656, -0.17987174,
        0.23184847,  0.52091815, -0.854295  , -0.03848413,  0.50941979,
       -0.24300541, -0.34452552, -0.38794493, -0.42666608,  0.2376849 ,
       -0.86125412,  0.1045995 ,  0.35182087,  0.50803605,  0.8635362 ,
       -0.79130248,  0.71127954, -0.56736363,  0.58748767,  0.71921854,
        0.92602826,  0.96910812,  0.76775864,  0.23111744, -0.59978151,
        0.64808375,  0.70135272,  0.57972908,  0.80206029, -0.48997565,
       -0.39281988,  0.1559076 ,  0.37692183,  0.78414623, -0.49503013,
       -0.14392601, -0.83976928, -0.63330051,  0.22152952, -0.01281044,
       -0.74729102, -0.72387896, -0.42484553,  0.45119885,  0.99051997,
       -0.15372373,  0.73258519,  0.66887787, -0.9998173 , -0.59

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [78]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))


def distance_faster(P0, P1, p):
    # Author: Hemanth Pasupuleti
    # Reference: https://mathworld.wolfram.com/Point-LineDistance2-Dimensional.html

    v = P1 - P0
    v[:, [0, 1]] = v[:, [1, 0]]
    v[:, 1] *= -1 #求解法向量
    norm = np.linalg.norm(v, axis=1)
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i", r, v)) / norm

    return d
print(distance_faster(P0, P1, p))

[6.12104264 5.3530494  4.0557445  1.35151028 2.15723018 7.52101825
 2.03384108 3.03273539 3.35563731 2.28570398]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [79]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))


# Author: Yang Wu (Broadcasting)
def distance_points_to_lines(
    p: np.ndarray, p_1: np.ndarray, p_2: np.ndarray
) -> np.ndarray:
    x_0, y_0 = p.T  # Shape -> (n points, )
    x_1, y_1 = p_1.T  # Shape -> (n lines, )
    x_2, y_2 = p_2.T  # Shape -> (n lines, )

    # Displacement vector coordinates from p_1 -> p_2
    dx = x_2 - x_1  # Shape -> (n lines, )
    dy = y_2 - y_1  # Shape -> (n lines, )

    # The 'cross product' term
    cross_term = x_2 * y_1 - y_2 * x_1  # Shape -> (n lines, )

    # Broadcast x_0, y_0 (n points, 1) and dx, dy, cross_term (1, n lines) -> (n points, n lines)
    numerator = np.abs(
        dy[np.newaxis, :] * x_0[:, np.newaxis]
        - dx[np.newaxis, :] * y_0[:, np.newaxis]
        + cross_term[np.newaxis, :]
    )
    denominator = np.sqrt(dx**2 + dy**2)  # Shape -> (n lines, )

    # Shape (n points, n lines) / (1, n_lines) -> (n points, n lines)
    return numerator / denominator[np.newaxis, :]


distance_points_to_lines(p, P0, P1)


NameError: name 'distance' is not defined

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
windowed = sliding_window_view(Z, window_shape=4)
print(windowed)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
Z=np.eye(3)
Z = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [2, 4, 6], 
    ]
)
print(np.linalg.matrix_rank(Z))

2


#### 83. How to find the most frequent value in an array?

In [ ]:
Z=[1,1,2,2,3,3,4,4,4,5,5,5,5]
indices=np.bincount(Z).argmax()
print(indices)

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0, 10, (10, 10))
blocks = sliding_window_view(Z, window_shape=(3, 3))
print(Z)
print(blocks)
print("原矩阵的形状:", Z.shape)
print("提取后矩阵的形状:", blocks.shape)

[[6 5 6 3 5 6 7 2 7 2]
 [8 2 1 9 4 4 8 8 4 2]
 [4 8 0 3 6 4 7 3 5 0]
 [4 6 8 4 1 8 9 8 1 7]
 [6 9 4 1 0 4 4 9 9 0]
 [2 8 6 6 8 7 7 4 7 0]
 [0 1 1 0 2 6 3 9 2 5]
 [5 3 1 1 8 5 2 2 9 0]
 [5 4 9 4 2 4 4 8 2 5]
 [3 9 1 5 0 3 9 8 7 3]]
[[[[6 5 6]
   [8 2 1]
   [4 8 0]]

  [[5 6 3]
   [2 1 9]
   [8 0 3]]

  [[6 3 5]
   [1 9 4]
   [0 3 6]]

  [[3 5 6]
   [9 4 4]
   [3 6 4]]

  [[5 6 7]
   [4 4 8]
   [6 4 7]]

  [[6 7 2]
   [4 8 8]
   [4 7 3]]

  [[7 2 7]
   [8 8 4]
   [7 3 5]]

  [[2 7 2]
   [8 4 2]
   [3 5 0]]]


 [[[8 2 1]
   [4 8 0]
   [4 6 8]]

  [[2 1 9]
   [8 0 3]
   [6 8 4]]

  [[1 9 4]
   [0 3 6]
   [8 4 1]]

  [[9 4 4]
   [3 6 4]
   [4 1 8]]

  [[4 4 8]
   [6 4 7]
   [1 8 9]]

  [[4 8 8]
   [4 7 3]
   [8 9 8]]

  [[8 8 4]
   [7 3 5]
   [9 8 1]]

  [[8 4 2]
   [3 5 0]
   [8 1 7]]]


 [[[4 8 0]
   [4 6 8]
   [6 9 4]]

  [[8 0 3]
   [6 8 4]
   [9 4 1]]

  [[0 3 6]
   [8 4 1]
   [4 1 0]]

  [[3 6 4]
   [4 1 8]
   [1 0 4]]

  [[6 4 7]
   [1 8 9]
   [0 4 4]]

  [[4 7 3]
   [8 9 8]
   [4 4 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [81]:
# 第一部分：定义“对称”门派的专属类
class Symetric(np.ndarray):
    # 劫持赋值操作 (核心神经系统)
    def __setitem__(self, index, value):
        i, j = index

        # 1. 呼叫老子 (np.ndarray) 把原始坐标 [i, j] 的值改掉
        super().__setitem__((i, j), value)

        # 2. 魔法联动：把镜像坐标 [j, i] 的值也改掉
        super().__setitem__((j, i), value)


# 第二部分：定义一个“开光”辅助函数
def symetric(Z):
    # 1. 纯数学操作：原矩阵 + 转置矩阵 - 对角线补偿，强行打造出完美的对称数据
    sym_math = Z + Z.T - np.diag(Z.diagonal())

    # 2. 底层黑客操作：不复制内存，直接给它披上 Symetric 类的外衣
    return np.asarray(sym_math).view(Symetric)


# --- 🚀 见证奇迹的实战测试 ---

# 1. 随机生成一个普通的 5x5 矩阵
Z = np.random.randint(0, 10, (5, 5))
print("原始随机矩阵:")
print(Z)

# 2. 将其转换为超能力对称矩阵
S = symetric(Z)
print("\n强行转换后的对称矩阵:")
print(S)

# 3. 触发联动神经！修改第 2 行，第 4 列
print("\n🚨 执行赋值指令: S[2, 4] = 99")
S[2, 4] = 99

print("\n触发魔法后的矩阵:")
print(S)


原始随机矩阵:
[[6 6 4 9 2]
 [5 1 4 1 0]
 [6 8 7 0 0]
 [2 8 7 4 4]
 [9 8 8 6 3]]

强行转换后的对称矩阵:
[[ 6 11 10 11 11]
 [11  1 12  9  8]
 [10 12  7  7  8]
 [11  9  7  4 10]
 [11  8  8 10  3]]

🚨 执行赋值指令: S[2, 4] = 99

触发魔法后的矩阵:
[[ 6 11 10 11 11]
 [11  1 12  9  8]
 [10 12  7  7 99]
 [11  9  7  4 10]
 [11  8 99 10  3]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
class Symetric(np.ndarray):
    # 2. 劫持赋值操作 (比如当你执行 S[2, 3] = 42 时，会触发这个方法)
    def __setitem__(self, index, value):
        i, j = index
        # 第一步：老老实实把原来的 [i, j] 赋值
        super().__setitem__((i, j), value)
        # 第二步：魔法发生！强行把镜像位置 [j, i] 也赋上相同的值
        super().__setitem__((j, i), value)


# 3. 辅助函数：把普通矩阵变成我们自定义的对称矩阵
def symetric(Z):
    # 数学操作：强制把普通矩阵变成对称矩阵 (Z + Z的转置 - 对角线重复部分)
    sym_math = Z + Z.T - np.diag(Z.diagonal())
    # 核心降维打击：用 .view() 强行让 NumPy 把这块内存认作我们写的 Symetric 类！
    return np.asarray(sym_math).view(Symetric)
Z = np.random.randint(0, 10, (5, 5))

# 转换成我们的超能力对称矩阵
S = symetric(Z)

print("--- 初始的对称矩阵 ---")
print(S)

# 触发魔法！修改第 1 行，第 3 列
print("\n>>> 执行 S[1, 3] = 99")
S[1, 3] = 99

print("\n--- 修改后的矩阵 ---")
print(S)

--- 初始的对称矩阵 ---
[[ 6  6  7  4 15]
 [ 6  5 13  7  9]
 [ 7 13  3  4 16]
 [ 4  7  4  6 18]
 [15  9 16 18  1]]

>>> 执行 S[1, 3] = 99

--- 修改后的矩阵 ---
[[ 6  6  7  4 15]
 [ 6  5 13 99  9]
 [ 7 13  3  4 16]
 [ 4 99  4  6 18]
 [15  9 16 18  1]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16, 16))
blocks = sliding_window_view(Z, window_shape=(4, 4))[::4, ::4]
print(blocks)
block_sum = blocks.sum(axis=(-2, -1))
print("块求和的结果形状:", block_sum.shape)  # 输出: (4, 4)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
 

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)